name: Repository Dispatch
env:
  QT_VERSION:     "5.15.2"
  MINGW_VERSION:  "win32_mingw81"
  MINGW_PATH:     "mingw81_32"
  BUILD_TYPE:      Release
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: windows-latest
    steps:
    -
      uses: actions/checkout@v2
      with: 
         repository: mhogomchungu/media-downloader    
         path: MD
    -
     name: Uninstall packages
     run: |
         choco uninstall strawberryperl --force
    -
      name: Install correct version of mingw
      uses: msys2/setup-msys2@v2
      with:
            install: mingw-w64-i686-gcc
            msystem: mingw32        
    -
      name: update env
      run:  echo "D:/a/_temp/msys64/mingw32/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    -
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"
        host: 'windows'
        target: 'desktop'
    -
      name: Check GCC version and path
      run: |
          Write-Output (Get-Command c++.exe).Path
          c++.exe --version
    -
      name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: "${{github.workspace}}/qt/Qt/${{ env.QT_VERSION }}"
        msystem: MINGW32
      run: cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -S ${{github.workspace}}/MD/ -B ${{github.workspace}}/MD/build
    -
      name: Build Project
      run: cmake --build ${{github.workspace}}/MD/build
    -
      name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
       path: ${{github.workspace}}\MD\build\media-downloader.exe
       
