name: Repository Dispatch
env:
  QT_VERSION:     "5.15.2"
  MINGW_VERSION:  "win32_mingw81"
  MINGW_PATH:     "mingw81_32"
  BUILD_TYPE:      Release
on:
  repository_dispatch:
    types: [PublishGit]
jobs:
  myEvent:
    runs-on: windows-latest
    steps:
    -
      uses: actions/checkout@v2
      with:
         repository: mhogomchungu/media-downloader
         path: MD
    -
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"
        host: 'windows'
        target: 'desktop'
        tools: 'tools_mingw1310'
    -
      name: Update gcc path
      run: |
          echo "${{github.workspace}}/qt/Qt/Tools/mingw1310_32/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    -
      name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: "${{github.workspace}}/qt/Qt/${{ env.QT_VERSION }}"
        msystem: MINGW32
      run: cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -S ${{github.workspace}}/MD/ -B ${{github.workspace}}/MD/build
    -
      name: Build Project
      run: cmake --build ${{github.workspace}}/MD/build
    -
      name: Make release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{github.workspace}}/MD/build/media-downloader.exe
        tag: "First"
        commit: "94951c8"
        allowUpdates: true
