name: Repository Dispatch
env:
  QT_VERSION:     "5.15.2"
  MINGW_VERSION:  "win32_mingw81"
  MINGW_PATH:     "mingw81_32"
  BUILD_TYPE:      Release
on:
  repository_dispatch:
    types: [PublishGit]
jobs:
  myEvent:
    runs-on: windows-latest
    steps:
    -
      uses: actions/checkout@v4
      with: 
         repository: mhogomchungu/media-downloader    
         path: MD
    -
      name: Install mingw
      uses: msys2/setup-msys2@v2
      with:
            install: mingw-w64-i686-gcc
            msystem: mingw32   
            location: ${{github.workspace}}
    -
      name: update env
      run: echo "${{github.workspace}}/msys64/mingw32/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    -
      name: Check GCC version and path
      run: |
          Write-Output (Get-Command c++.exe).Path
          c++.exe --version 
    -
      name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"
        host: 'windows'
        target: 'desktop'
    -
      name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: "${{github.workspace}}/qt/Qt/${{ env.QT_VERSION }}"
        msystem: MINGW32
      run: cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -S ${{github.workspace}}/MD/ -B ${{github.workspace}}/MD/build
    -
      name: Build Project
      run: cmake --build ${{github.workspace}}/MD/build
    -
      name: Prepare Release
      run: |
        New-Item -ItemType Directory -Path ${{github.workspace}}\MediaDownloader.git
        New-Item -ItemType Directory -Path ${{github.workspace}}\MediaDownloader.git/local
        Copy-Item -Path ${{github.workspace}}\MD\translations -Destination ${{github.workspace}}\MediaDownloader.git -Recurse
        Copy-Item -Path ${{github.workspace}}\MD\build\media-downloader.exe -Destination ${{github.workspace}}\MediaDownloader.git
        Set-Location ${{github.workspace}}\MediaDownloader.git
        
        ${{github.workspace}}/qt/Qt/${{ env.QT_VERSION }}/${{ env.MINGW_PATH }}/bin/windeployqt.exe ${{github.workspace}}\MediaDownloader.git\media-downloader.exe
              
        Invoke-WebRequest "https://github.com/mhogomchungu/media-downloader-git/releases/download/0.0.0/3rdParty.zip" -OutFile ${{github.workspace}}\MediaDownloader.git\3rdParty.zip
        Invoke-WebRequest "https://github.com/mhogomchungu/media-downloader-git/releases/download/0.0.0/libs.zip" -OutFile ${{github.workspace}}\MediaDownloader.git\libs.zip

        Expand-Archive -Path ${{github.workspace}}\MediaDownloader.git\3rdParty.zip -DestinationPath ${{github.workspace}}\MediaDownloader.git
        Expand-Archive -Path ${{github.workspace}}\MediaDownloader.git\libs.zip -DestinationPath ${{github.workspace}}

        Copy-Item ${{github.workspace}}\libs -Destination ${{github.workspace}}\MediaDownloader.git -Recurse
        
        Remove-Item -Path ${{github.workspace}}\MediaDownloader.git\libs.zip
        Remove-Item -Path ${{github.workspace}}\MediaDownloader.git\3rdParty.zip

        Compress-Archive -Path ${{github.workspace}}\MediaDownloader.git -DestinationPath ${{github.workspace}}\MediaDownloader.git.zip

        echo "CURRENT_TIME=$((Get-Date).ToString())" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    -
      name: Make release      
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{github.workspace}}\MediaDownloader.git.zip
        tag: "0.0.0"
        commit: "main"  
        allowUpdates: true
        body: "Build date and time: ${{ env.CURRENT_TIME }}\n\n\"MediaDownloader.git.zip\" archive contains portable version of the latest git changes."
