name: Repository Dispatch MacOS
env:
  QT6_VERSION:     "6.6.2"
on:
  repository_dispatch:
    types: [PublishMacGit]
jobs:
  buildMacGitEvent:
    runs-on: macos-latest
    steps:
    -
      uses: actions/checkout@v4
      with:
         repository: mhogomchungu/media-downloader
         path: MAC
    -
      name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT6_VERSION }}
        arch: 'clang_64'
        dir: "${{github.workspace}}/qt6"
        install-deps: "true"
        host: 'mac'
        target: 'desktop'
    -
      name: Check presence of supporting tools
      run: |
          which clang++
          clang++ --version
    -
      name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: "${{github.workspace}}/qt6/Qt/${{ env.QT6_VERSION }}"
      run: cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/media-downloader -DBUILD_WITH_QT6=true -DOUTPUT_BASE_NAME=MediaDownloaderQt6 -DLIBRARIES_LOCATION=${{github.workspace}}/MediaDownloader.git/ -DOUTPUT_PATH=${{github.workspace}}/ -DSOURCE_PATH=${{github.workspace}}/MAC/ -DCMAKE_VERBOSE_MAKEFILE=FALSE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}}/MAC/ -B ${{github.workspace}}/MAC/build6
    -
      name: Build
      run: cmake --build ${{github.workspace}}/MAC/build6
    -
      name: Download 3rdParty Apps
      run: |
           mkdir ${{github.workspace}}/MAC/build6/media-downloader.app/Contents/MacOS/extra
           aria2c -d ${{github.workspace}}/MAC/build6/media-downloader.app/Contents/MacOS/extra https://github.com/yt-dlp/yt-dlp/releases/download/2024.04.09/yt-dlp_macos
           aria2c -d ${{github.workspace}}/MAC/build6/media-downloader.app/Contents/MacOS/extra https://github.com/mhogomchungu/media-downloader-git/releases/download/0.0.0/ffmpeg.macos.zip
           cd ${{github.workspace}}/MAC/build6/media-downloader.app/Contents/MacOS/extra
           tar -xf ffmpeg.macos.zip
           rm -rf ffmpeg.macos.zip
    -
      name: Create .img Bundle
      run: ${{github.workspace}}/qt6/Qt/${{ env.QT6_VERSION }}/macos/bin/macdeployqt6 ${{github.workspace}}/MAC/build6/media-downloader.app -dmg
    -
      name: Zip app
      run: 7z a ${{github.workspace}}/MAC/build6/media-downloader.app.zip ${{github.workspace}}/MAC/build6/media-downloader.app
    -
      name: Post Bundle
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{github.workspace}}/MAC/build6/media-downloader.dmg,${{github.workspace}}/MAC/build6/media-downloader.app.zip
        tag: "0.0.0"
        commit: "main"
        allowUpdates: true
        omitBody: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true
